# Generated by Django 5.1.2 on 2024-11-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest_user',
            old_name='Email',
            new_name='email',
        ),
    ]
